services:
  server:
    user: root # resolve file system permission issue 
    build:
      context: .
    env_file:
      - .env
    ports:
      - 8000:8000
    networks:
      - app-network
      - redis-network
    depends_on:
      db:
        condition: service_healthy
        
  db:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - /var/lib/postgresql/data
    env_file:
      - .env.postgres
    expose: # exposes postgres to other docker containers
      - 5432
    ports: # exposes postgres to host
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge
  redis-network:
    external: true
